name: massai mara park 01 multiple jobs

on:
  workflow_dispatch

jobs:
  build:
    name: build JAR
    runs-on: ubuntu-22.04
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application.jar
          path: ./build/libs/*SNAPSHOT.jar

  deploy:
    name: deploy & test
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: application.jar

      - name: Check downloaded files
        run: ls -al

      - name: Run Spring Boot JAR in background
        run: |
          nohup java -jar ./*.jar > app.log 2>&1 &
          sleep 20

      - name: Test endpoint - /
        run: curl http://localhost:8080 || exit 1

      - name: Test endpoint - /images
        run: curl http://localhost:8080/images || exit 1

      - name: Test endpoint - /animal
        run: curl http://localhost:8080/animal || exit 1